name: Build and Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends cpanminus libncurses-dev libsqlite3-dev
      - name: Install Perl dependencies
        run: sudo cpanm --notest --installdeps . && sudo chown -R "$USER:$USER" .
      - name: Build
        run: perl Makefile.PL && make
      - name: Test
        run: make test
